module.exports = function padronizarDadosAnimal(animal) {
  return {
    numero: animal.numero || '',
    brinco: animal.brinco || '',
    nascimento: animal.nascimento || '',
    idade: animal.idade || '',
    categoria: animal.categoria || '',
    origem: animal.origem || '',
    raca: animal.raca || '',
    grupo: animal.grupo || '',
    status: animal.status || 'ativo',
    dataSaida: animal.dataSaida || null,
    motivoSaida: animal.motivoSaida || '',
    observacaoSaida: animal.observacaoSaida || '',
    partos: animal.partos || [],
    numeroPartos: animal.numeroPartos || 0,
    ultimaIA: animal.ultimaIA || '',
    ultimoParto: animal.ultimoParto || '',
    lactacoes: animal.lactacoes || [],
    tratamentos: animal.tratamentos || [],
    ocorrencias: animal.ocorrencias || [],
    pesagens: animal.pesagens || [],
    producaoLeite: animal.producaoLeite || [],
    descartado: animal.descartado || false,
  };
};
